// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package model

import (
	core "terraform/terraform-provider/provider/tf/core/model"

	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ core.TFModel = &SmtpSubscriptionTFModel{}

type SmtpSubscriptionTFModel struct {
	// ID is auto-generated by the API
	ID types.String `tfsdk:"id"`

	// Required fields
	Name            types.String `tfsdk:"name"`
	IntegrationName types.String `tfsdk:"integration_name"`
	Recipients      types.List   `tfsdk:"recipients"` // List of email strings
	Filters         types.List   `tfsdk:"filters"`    // List of FilterTFModel objects

	// Optional fields
	Enabled types.Bool `tfsdk:"enabled"`
}

// FilterTFModel represents a filter object in the subscription.
// Used only as a Go-side target for ElementsAs; the schema is the source of truth for required/optional.
type FilterTFModel struct {
	Category types.String `tfsdk:"category"` // Required
	Type     types.String `tfsdk:"type"`     // Required
	Status   types.String `tfsdk:"status"`   // Optional
}

func (s *SmtpSubscriptionTFModel) GetName() string {
	return s.Name.ValueString()
}
