// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package schema

import (
	"terraform/terraform-provider/provider/common/attribute"
	coreschema "terraform/terraform-provider/provider/tf/core/schema"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

type SmtpSubscriptionSchema struct{}

var _ coreschema.ResourceSchema = &SmtpSubscriptionSchema{}

func (s *SmtpSubscriptionSchema) GetSchema() schema.Schema {
	builder := coreschema.NewSchemaBuilder()

	builder.AddMarkdownDescription("SMTP Subscription resource for managing email notification subscriptions")

	builder.AddAttribute("id", schema.StringAttribute{
		MarkdownDescription: "Unique identifier of the subscription (auto-generated by API)",
		Computed:            true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	})

	builder.AddAttribute("name", schema.StringAttribute{
		MarkdownDescription: "Name of the SMTP subscription for identification and auditing",
		Required:            true,
	})

	builder.AddAttribute("integration_name", schema.StringAttribute{
		MarkdownDescription: "Name of the SMTP integration this subscription belongs to (cannot be modified after creation)",
		Required:            true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.RequiresReplace(),
		},
	})

	builder.AddAttribute("recipients", schema.ListAttribute{
		MarkdownDescription: "List of email addresses that will receive notifications (minimum 1 required)",
		Required:            true,
		ElementType:         types.StringType,
		Validators: []validator.List{
			listvalidator.SizeAtLeast(1),
		},
	})

	builder.AddAttribute("filters", schema.ListNestedAttribute{
		MarkdownDescription: "Filter rules that determine which events trigger notifications",
		Required:            true,
		NestedObject: schema.NestedAttributeObject{
			Attributes: map[string]schema.Attribute{
				"category": schema.StringAttribute{
					MarkdownDescription: "Event category (e.g., ACTION, ALARM, BOT, TIME_TRIGGER)",
					Required:            true,
				},
				"type": schema.StringAttribute{
					MarkdownDescription: "Event type (e.g., TRIGGER)",
					Required:            true,
				},
				"status": schema.StringAttribute{
					MarkdownDescription: "Event status (e.g., EXECUTING) - optional",
					Optional:            true,
				},
			},
		},
	})

	builder.AddAttribute("enabled", schema.BoolAttribute{
		MarkdownDescription: "Whether the subscription is active (default: true)",
		Optional:            true,
		Computed:            true,
		Default:             booldefault.StaticBool(true),
	})

	return builder.Build()
}

// GetFieldComparisonRules returns the field comparison rules used when diffing TF state vs API state.
func (s *SmtpSubscriptionSchema) GetFieldComparisonRules() map[string]coreschema.FieldComparisonRule {
	return coreschema.DefaultFieldComparisonRules()
}

func (s *SmtpSubscriptionSchema) GetCompatibilityOptions() map[string]attribute.CompatibilityOptions {
	return map[string]attribute.CompatibilityOptions{
		"id": {
			MinVersion: "release-29.1.21",
		},
		"name": {
			MinVersion: "release-29.1.21",
		},
		"integration_name": {
			MinVersion: "release-29.1.21",
		},
		"recipients": {
			MinVersion: "release-29.1.21",
		},
		"filters": {
			MinVersion: "release-29.1.21",
		},
		"enabled": {
			MinVersion: "release-29.1.21",
		},
	}
}
