# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (hashicorp/ghaction-import-gpg) that assumes you set your 
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step 
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Debug Info
        run:  |
          lsb_release -a || /bin/true
          apt list --installed | grep gpg || /bin/true
          pgrep gpg-agent || /bin/true
          gpgconf --list-dirs agent-ssh-socket || /bin/true
          ls -al `gpgconf --list-dirs agent-ssh-socket` || /bin/true
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.23.4'
      -
        name: Import GPG key and configure for goreleaser
        id: import_gpg
        run: |
          # Create a secure temporary directory
          TEMP_DIR="$(mktemp -d -t gpg-XXXXXXXXXX)"
          chmod 700 "$TEMP_DIR"
          
          # Write key to file
          KEYFILE="$TEMP_DIR/private.key"
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > "$KEYFILE"
          chmod 600 "$KEYFILE"
          
          # Import key
          gpg --batch --import "$KEYFILE"
          
          # Setup GPG to use passphrase non-interactively
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
          echo "pinentry-mode loopback" > ~/.gnupg/gpg.conf
          gpg-connect-agent reloadagent /bye
          
          # Get fingerprint for goreleaser
          FINGERPRINT=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
          echo "fingerprint=$FINGERPRINT" >> $GITHUB_OUTPUT
          
          # Clean up
          shred -u "$KEYFILE" 2>/dev/null || rm -f "$KEYFILE"
          rm -rf "$TEMP_DIR"
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.1
        with:
          version: '~> v2'
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSWORD: ${{ secrets.PASSPHRASE }}  # GoReleaser will use this for signing

